apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-gitactions
  # - dependencies/db/db-service.yaml
  # - dependencies/memcached/memcached-service.yaml
resources:
- app/app-deployment.yaml
- app/app-service.yaml
- app/app-ingress.yaml
- dependencies/db/db-config.yaml
- dependencies/db/db-deployment.yaml
- dependencies/memcached/memcached-config.yaml
- dependencies/memcached/memcached-deployment.yaml
- dependencies/rabbitmq/rabbitmq-deployment.yaml
- dependencies/rabbitmq/rabbitmq-service.yaml
labels:
- includeSelectors: true
  pairs:
    project: gitops-gitactions
