apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  labels:
    app: vpromc
spec:
  type: ClusterIP
  selector:
    app: vpromc
  ports:
    - name: memcached
      port: 11211
      targetPort: 11211
      protocol: TCP